### PR TITLE
Added a grand-total badge of downloads

### PR DESCRIPTION
**Pull request by talgalili**
Added a grand-total badge of downloads (from RStudio logs)

### CODE REVIEW

**Comment by sjmgarnier** [comment]
@talgalili Is there a particular reason for making this change?

**Comment by talgalili** [comment]
Only that it is interesting.
I use the same badge here:
https://github.com/talgalili/dendextend/
https://github.com/talgalili/installr/

And think it is an interesting addition to the download per month badge.

**Comment by sjmgarnier** [comment]
Alright. Could you please rewrite the added line so that it matches the formatting used by @noamross for the other badges? Thanks.

**Comment by talgalili** [comment]
Tried again, I hope that was what you meant.

**Comment by sjmgarnier** [comment]
Thanks. It's just for consistency. Merging now.

**Pull request merged**
